---
- name: backup facts
  set_fact:
    __org_ansible_user: "{{ ansible_user | default(omit) }}"
    __org_ansible_ssh_pass: "{{ ansible_ssh_pass | default(omit) }}"
    __org_ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | default(omit) }}"
    __org_ansible_become_pass: "{{ ansible_become_pass | default(omit) }}"
  # check_mode でこの role が実行された場合、 poweruser_name で指定されたユーザは作成されない。
  # このため、後続の role のチェックを成功させるために poweruser_default_user のユーザのまま処理を実行する必要があるので
  # restore facts task を実行してはならなくなり、それによりこの backup facts task を実行する必要がなくなるのでスキップする。
  when: not ansible_check_mode

# デフォルト値 (defaults/main.yml の値) を利用する場合、 ansible_user の値を変更する前に poweruser_name の値を確定しておく必要がある。
- name: ensure poweruser_name
  set_fact:
    poweruser_name: "{{ poweruser_name }}"

# デフォルト値 (defaults/main.yml の値) を利用する場合、 ansible_ssh_pass や ansible_become_pass の値を変更する前に poweruser_password の値を確定しておく必要がある。
- name: ensure poweruser_password
  set_fact:
    poweruser_password: "{{ poweruser_password }}"

- name: set ansible_user
  set_fact:
    ansible_user: "{{ poweruser_default_user }}"
  when: poweruser_default_user is defined

- name: set ansible_ssh_pass
  set_fact:
    ansible_ssh_pass: "{{ poweruser_default_ssh_pass }}"
  when: poweruser_default_ssh_pass is defined

- name: set ansible_ssh_private_key_file
  set_fact:
    ansible_ssh_private_key_file: "{{ poweruser_default_ssh_private_key_file }}"
  when: poweruser_default_ssh_private_key_file is defined

- name: set ansible_become_pass
  set_fact:
    ansible_become_pass: "{{ poweruser_default_become_pass }}"
  when: poweruser_default_become_pass is defined

- name: create group of poweruser
  group:
    name: "{{ poweruser_group }}"
    gid: "{{ poweruser_gid | default(omit) }}"
    state: present
  become: true
  when: poweruser_group is defined

- name: create poweruser
  user:
    name: "{{ poweruser_name }}"
    group: "{{ poweruser_group | default(omit) }}"
    groups: "{{ poweruser_groups | default(omit) }}"
    password: "{{ poweruser_password | password_hash('sha512') }}"
    uid: "{{ poweruser_uid | default(omit) }}"
    state: present
  become: true
  ignore_errors: "{{ ansible_check_mode and poweruser_group is defined }}"

- name: update ansible_ssh_pass and ansible_become_pass if needed
  set_fact:
    ansible_ssh_pass: "{{ poweruser_password }}"
    ansible_become_pass: "{{ poweruser_password }}"
  when: ansible_user == poweruser_name

- name: add authorized_keys
  authorized_key:
    user: "{{ poweruser_name }}"
    key: "{{ item }}"
  loop: "{{ poweruser_authorized_keys | list }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: poweruser_authorized_keys is defined

- name: config sudoers
  lineinfile:
    path: "{{ poweruser_sudoers_file }}"
    regexp: "^{{ poweruser_name }} "
    line: "{{ poweruser_name }} ALL={{ '(ALL) NOPASSWD:' if poweruser_sudoers_nopasswd else '(ALL:ALL)' }} ALL"
    validate: 'visudo -cf %s'
    create: true
    state: present
  become: true
  when: poweruser_sudoers_configure

- name: restore facts
  set_fact:
    ansible_user: "{{ __org_ansible_user | default(omit) }}"
    ansible_ssh_pass: "{{ __org_ansible_ssh_pass | default(omit) }}"
    ansible_ssh_private_key_file: "{{ __org_ansible_ssh_private_key_file | default(omit) }}"
    ansible_become_pass: "{{ __org_ansible_become_pass | default(omit) }}"
  # backup facts task に記載のコメントと同様の理由により、 check_mode 時には restore facts task をスキップする。
  when: not ansible_check_mode
